# Generated by Django 3.1.7 on 2021-03-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_subject_videolink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='video_link',
        ),
        migrations.AddField(
            model_name='subject',
            name='video_link',
            field=models.ManyToManyField(to='trading.VideoLink'),
        ),
    ]
