# Generated by Django 3.1.7 on 2021-03-25 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_auto_20210325_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=10)),
                ('total_profit', models.CharField(max_length=10)),
                ('total_loss', models.CharField(max_length=10)),
                ('detail_report_email', models.CharField(max_length=100)),
                ('profit_violated', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.tradinguser')),
            ],
        ),
    ]
