# Generated by Django 3.1.7 on 2021-03-25 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_auto_20210325_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlystatistic',
            name='status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.status'),
        ),
    ]
