# Generated by Django 3.1.7 on 2021-03-25 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_auto_20210325_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=500)),
                ('year', models.CharField(max_length=100)),
                ('profit', models.CharField(max_length=500)),
                ('life_account_funded', models.CharField(max_length=200)),
                ('Payout', models.CharField(max_length=100)),
                ('Withdrawn', models.CharField(max_length=100)),
                ('Balance', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.tradinguser')),
            ],
        ),
    ]
