# Generated by Django 3.1.7 on 2021-03-25 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Balance',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Payout',
            new_name='payout',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Withdrawn',
            new_name='withdrawn',
        ),
    ]
